.TH GradeMan "1" "3.3.0" "class management for teachers"

.SH NAME
GradeMan \- class management database for teachers.
Since 

.SH SYNOPSIS
\fBGradeMan\fR\fR

.SH DESCRIPTION
GradeMan manages your student grades and your entire class organization.

.SH OPTIONS
.IP "\f[none]\fR" 4
There are no command line options, since GradeMan is a GUI software

.SH HOMEPAGE
More information about GradeMan can be found at <\fIhttp://grademan.polarwinkel.de/\fR>.

.SH AUTHOR
GradeMan was written by Dirk Winkel <\fIit@polarwinkel.de\fR>.
